# Mongoid configuration file
# More info at:
# http://mongoid.org/en/mongoid/docs/installation.html#configuration
development:
  sessions:
    default:
      database: hammock_dev
      hosts:
        - localhost:27017
